[window]
opacity = 0.9
decorations = "None"
padding = { x = 6, y = 6 }

[font]
size = 12

[font.normal]
family = "HackGen Console NF"
style = "Regular"

[font.bold]
family = "HackGen Console NF"
style = "Bold"

[font.bold_italic]
family = "HackGen Console NF"
style = "Bold Italic"

[font.italic]
family = "HackGen Console NF"
style = "Italic"

[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night_storm.toml"
    # "~/.config/alacritty/dank-theme.toml"
]

[scrolling]
history = 3023

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
unfocused_hollow = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = false

[bell]
duration = 0

[keyboard]
bindings = [
  { key = "C",       mods = "Control|Shift", action = "Copy"  },
  { key = "V",       mods = "Control|Shift", action = "Paste" },
  { key = "N",       mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Equals",  mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus",   mods = "Control",       action = "DecreaseFontSize" },
  { key = "Key0",    mods = "Control",       action = "ResetFontSize"    },
  { key = "Enter",   mods = "Shift",         chars = "\n" },
]
