add_newline = false

[character]
# success_symbol = "[â¯](bold green)"
# error_symbol   = "[â¯](bold red)"
# vicmd_symbol   = "[â®](bold green)"
success_symbol = "[>](bold green)"
error_symbol   = "[X](bold red)"
vicmd_symbol   = "[V](bold green)"

[nodejs]
detect_extensions = []
detect_folders = []
detect_files = ["package.json"]

[aws]
format = ''
# format = 'on [$symbol$profile]($style) '
# style = 'bold blue'
# symbol = 'ðŸ…° '
